### ISSUE TITLE
"Attempt to subtract with overflow"

### ISSUE THREAD

**Issue by simoncozens** [cmyr/fea-rs#18]
Trying to compile the attached features file got this backtrace:

```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/simon/hacks/typography/fea-rs/fea-rs/src/util/highlighting.rs:126:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c7bc5e33c25e29058cbafefe680da8d5e9220e9/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/2c7bc5e33c25e29058cbafefe680da8d5e9220e9/library/core/src/panicking.rs:96:14
   2: core::panicking::panic
             at /rustc/2c7bc5e33c25e29058cbafefe680da8d5e9220e9/library/core/src/panicking.rs:50:5
   3: fea_rs::util::highlighting::write_line_error
             at /Users/simon/hacks/typography/fea-rs/fea-rs/src/util/highlighting.rs:126:21
   4: fea_rs::util::highlighting::stringify_errors
             at /Users/simon/hacks/typography/fea-rs/fea-rs/src/util/highlighting.rs:100:9
   5: fonticulus::features::print_diagnostics
             at ./src/features.rs:62:9
   6: fonticulus::features::compile_features
             at ./src/features.rs:23:13
   7: fonticulus::buildbasic::build_font
             at ./src/buildbasic.rs:146:5
   8: fonticulus::create_variable_font
             at ./src/main.rs:140:20
   9: fonticulus::main
             at ./src/main.rs:54:9
  10: core::ops::function::FnOnce::call_once
             at /rustc/2c7bc5e33c25e29058cbafefe680da8d5e9220e9/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[features.fea.txt](https://github.com/cmyr/fea-rs/files/7493202/features.fea.txt)

**Comment by simoncozens** [comment]
The error is an editing error, where the `feature frac {` was not correctly removed from the file.

**Comment by cmyr** [comment]
even with that error in place, I'm confused by this error, which I can't reproduce. I've seen this before, though; it's an off-by-one in the code that is trying to find the correct span in the file, for displaying an error message.
